### ISSUE TITLE
Potential error at line 509 in hyper2color.c ?

### ISSUE THREAD

**Issue by rexguo** [hyperspectral-calibration/hyper2color#1]
https://github.com/hyperspectral-calibration/hyper2color/blob/0d14ec1dfb84cc415f585152b46ac8742b74e9c9/src/hyper2color.c#L509

Hello, in hyper2color.c #509, Should Y_match be Z_match instead?

**Comment by ruven** [comment]
Thanks, you're right! I've just committed a fix (https://github.com/hyperspectral-calibration/hyper2color/commit/4a4383dd8b15f64e23605562deb9cdbe5fb45588).
